services:
  client:
    build:
      context: .
      dockerfile: ./Dockerfile-Dev
    command: ["npm", "run", "client:dev"]
    depends_on:
      - server
    environment:
      - BASE_URL=http://server:3000
    networks:
      - habitica
    ports:
      - "8080:8080"
    volumes:
      - data:/usr/src/habitica
      - node_modules:/usr/src/habitica/node_modules
      - client_node_modules:/usr/src/habitica/website/client/node_modules
  server:
    build:
      context: .
      dockerfile: ./Dockerfile-Dev
    command: ["npm", "start"]
    depends_on:
      - mongo
    environment:
      - NODE_DB_URI=mongodb://mongo/habitrpg
    networks:
      - habitica
    ports:
      - "3000:3000"
    volumes:
      - data:/usr/src/habitica
      - node_modules:/usr/src/habitica/node_modules
  mongo:
    image: mongo:3.6
    networks:
      - habitica
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
      - config_db:/data/configdb
networks:
  habitica:
    driver: bridge

volumes:
  data:
  node_modules:
  client_node_modules:
  db:
  config_db:
